openapi: 3.0.0

servers:
- description: Local dev
  url: http://127.0.0.1:9234

info:
  contact:
    url: https://github.com/chernyshev-alex/books-store
  description: REST APIs books service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: ToDo API
  version: 0.0.1

paths:
  /search/books:
    get:
      operationId:  BooksByAuthorId
      parameters:
      - in: query
        name: authorId
        required: true
        schema:
          type: string
      responses:
        "200":
          $ref: '#/components/responses/SearchBooksResponse'
        "400":
          $ref: '#/components/responses/ErrorResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'

  /books:
    post:
      operationId: AddBook
      summary: Add a new book
      requestBody:
          $ref:  '#/components/requestBodies/AddBookRequest'
      responses:
        "201":
          $ref: '#/components/responses/AddBookResponse'
        "400":
          $ref: '#/components/responses/ErrorResponse'
        "500":
          $ref: '#/components/responses/ErrorResponse'

  /books/{bookId}:
    delete:
      operationId: DeleteBook
      parameters:
        - $ref: "#/components/parameters/bookId"
      responses:
        "200":
          description: removed
        "404":
          description: not found
        "500":
          $ref: '#/components/responses/ErrorResponse'

components:
  parameters:
    bookId:
      in: path
      name:  bookId
      required: true
      schema:
        type: string
      description: book id
  
  requestBodies:
    AddBookRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BookJson'

  responses:
    AddBookResponse:
      description: add book response
      content:
        application/json:
          schema:
            required: [book]
            properties:
              book:
                $ref: '#/components/schemas/BookJson'

    SearchBooksResponse:
      description: search books response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BookJson'

    ErrorResponse:
      description: Response when errors happen.
      content:
        application/json:
          schema:
            required: [error]
            properties:
              error:
                type: string

  schemas:
    BookJson:
      type: object
      properties:
        id : 
          type: integer
        isbn:
          type: string
        title:
          type: string
        descr: 
          type: string
        publisherId:
          type: integer
        publisher:
          type: string
        authorId:
          type: integer
        author:
          type: string
        year:
          type: integer
      required: [id, isbn, title, descr, publisher, publisherId, author, authorId, year]

   

