http://127.0.0.1:8080/search/books?authorId=1000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjMSI6InJ3IiwiZm9vIjoiYmFyIn0.EjjRjUGjYSPx0JtPuWJP9NAjuqH0DS4b9BF0VPBP1N76uQ4a33ECniPbbmuLhdyxe33t8EVSbb7dGHXeIW2Lkkcgxmf4wlKP3XvS85NKIjAPR-LzD0mjRToSxhCyilN8XFamVF4osNSd9GZe5oHTO23zI_AreR-sJ4uO3Jb7tRhSTMphU_jXG4Pm-9CBxbOHbw6WPvLWjeGpRk2XT3XOyHn1ZLvLTNRPe1SW6thGX8TsFAjWYw5J43Toq5-MnR6qNe2EgzetlxoGBg2WS-CIp-hkpNqe68mpi-y8L5HszaLb_T6Hs-UGBw52NRCf8Bj56wigpPkCVg9CW-4UuT2oCQ
